# Generated by Django 4.0.2 on 2022-02-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Megami_app', '0002_alter_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_text', models.CharField(max_length=100)),
                ('good_count', models.IntegerField(default=0)),
            ],
        ),
    ]
