# Generated by Django 4.0.2 on 2022-02-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Megami_app', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='good_count',
            field=models.IntegerField(default=0),
        ),
    ]
