# Generated by Django 4.0.2 on 2022-02-08 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Megami_app', '0004_post_good_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
