# Generated by Django 4.0.2 on 2022-02-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Megami_app', '0006_chats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chats',
        ),
    ]
