# Generated by Django 4.0.2 on 2022-02-08 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Megami_account', '0002_user_good_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='good_count',
        ),
    ]
